### ISSUE TITLE
Error opening schematic in KiCad

### ISSUE THREAD

**Issue by SteveMoody73** [AidanHockey5/YM2151_VGM_STM32#1]
It looks like you're missing some library files. When opening the schematic in KiCad i get the following errors.

**The following libraries were not found:**

C:\Users\Aidan\Documents\KiCad_Custom_Libs\bluepill_breakouts
C:\Users\Aidan\Documents\Arduino\Teensy_3_5_VGM_Player_YM2612_SN76489\SchematicsAndInfo\Teensy_3_5_VGM_Player-cache
C:\Users\Aidan\Documents\KiCad_Custom_Libs\LM2596S-5.0
C:\Users\Aidan\Documents\KiCad_Custom_Libs\CH340G_D-SUN-V3.0-cache
C:\Users\Aidan\Documents\KiCad_Custom_Libs\VGM_Components_Library
C:\Users\Aidan\Documents\KiCad_Custom_Libs\TPA3122D2
C:\Users\Aidan\Documents\KiCad_Custom_Libs\DM3CS-SF
C:\Users\Aidan\Documents\KiCad_Custom_Libs\1825115Swit

**Comment by AidanHockey5** [comment]
Sorry about that. I'm still getting over KiCAD's miserable library system. All footprints/symbols should now be locally stored within the project folder and referenced relative to the project's location.
